version: "3.8"

services:
  react-s3-experiment:
    image: ghcr.io/${GITHB_ACTOR}/react-s3-experiment:latest
    container_name: react-s3-experiment-container
    ports:
      - "7000:80"
    restart: always